######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 16 18:01:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
PRECOMPILED_HEADER += stdafx.h

# Input
SOURCES += main.cpp \
    selectserver.cpp

HEADERS += \
    selectserver.h

